### ISSUE TITLE
Add exporter for FreeRadius MySQL

### ISSUE THREAD

**Issue by michael-batz** [michael-batz/yourCMDB#12]
A new exporter should be added for exporting values of a CMDB object to a FreeRadius database backend.
ToDos:
- [x] create exporter
- [x] tests
- [x] documentation

**Comment by andsch** [comment]
Please also provide a frontend to visualize accounting data! ... just for debugging purposes!

**Comment by michael-batz** [comment]
Finished first version.
ToDo:
- Tests
- Documentation

**Comment by michael-batz** [comment]
Implementation and documentation done. Now testing.

**Comment by michael-batz** [comment]
tests completed
