### ISSUE TITLE
ExportAPI: use CMDB object ID in export variables

### ISSUE THREAD

**Issue by michael-batz** [michael-batz/yourCMDB#20]
It would be nice, to use the yourCMDB object ID in the definition of export variables
See #17 for discussion.

**Comment by cehawe** [comment]
Cool :D Thanks! Any idea when this will be released?

**Comment by michael-batz** [comment]
The concept would be, to use the following special strings in export configuration:
- yourCMDB_object_id
- yourCMDB_object_type

e.g.
`
<variable name="hostvar_cmdbid">
<value objecttype="server" fieldname="yourCMDB_object_id" />
</variable>
`

The yourCMDB_* strings are reserved and not allowed to use as fieldname of an object. So that should work.

**Comment by michael-batz** [comment]
Implementation done, documentation needs to be updated

**Comment by cehawe** [comment]
Damn your quick! It works thanks!

**Comment by michael-batz** [comment]
Documentation done.
Thanks for the feedback, this will be included in the next release.
